version: '3'
services:
    charlie:
      build: .
      image: qureshi/ml
      user: $user_id:$group_id
      working_dir: /home/dockeruser
      stdin_open: true
      volumes:
        - /home/faisal/code/ml:/home/dockeruser/ml:rw
      tty: true
      ports: 
        - "8888:8888"
      group_add:
        - "1010"
      environment:
        - HOME="/home/dockeruser"
      deploy:
        resources:
          reservations:
            devices:
              - capabilities: [gpu]
