version: '3'
services:
    rr:
      build: .
      image: qureshi/sqlite3
      user: $user_id:$group_id
      working_dir: /home/dockeruser
      stdin_open: true
      volumes:
        - /home/faisal/code/sqlite3:/home/dockeruser/sqlite3:rw
      tty: true
      ports: 
        - "8888:8888"
      group_add:
        - "1010"
      environment:
        - HOME="/home/dockeruser"
